// Code generated by protoc-gen-go.
// source: howdy.proto
// DO NOT EDIT!

/*
Package howdy is a generated protocol buffer package.

It is generated from these files:
	howdy.proto

It has these top-level messages:
	HowdyRequest
	HowdyReply
*/
package howdy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// request message
type HowdyRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HowdyRequest) Reset()                    { *m = HowdyRequest{} }
func (m *HowdyRequest) String() string            { return proto.CompactTextString(m) }
func (*HowdyRequest) ProtoMessage()               {}
func (*HowdyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HowdyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// response message
type HowdyReply struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *HowdyReply) Reset()                    { *m = HowdyReply{} }
func (m *HowdyReply) String() string            { return proto.CompactTextString(m) }
func (*HowdyReply) ProtoMessage()               {}
func (*HowdyReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HowdyReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*HowdyRequest)(nil), "howdy.HowdyRequest")
	proto.RegisterType((*HowdyReply)(nil), "howdy.HowdyReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// sending a greeting
	SayHowdy(ctx context.Context, in *HowdyRequest, opts ...grpc.CallOption) (*HowdyReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHowdy(ctx context.Context, in *HowdyRequest, opts ...grpc.CallOption) (*HowdyReply, error) {
	out := new(HowdyReply)
	err := grpc.Invoke(ctx, "/howdy.Greeter/SayHowdy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// sending a greeting
	SayHowdy(context.Context, *HowdyRequest) (*HowdyReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHowdy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HowdyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHowdy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/howdy.Greeter/SayHowdy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHowdy(ctx, req.(*HowdyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "howdy.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHowdy",
			Handler:    _Greeter_SayHowdy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "howdy.proto",
}

func init() { proto.RegisterFile("howdy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc8, 0x2f, 0x4f,
	0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x94, 0xb8, 0x78, 0x3c,
	0x40, 0x8c, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc,
	0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x49, 0x8e, 0x8b, 0x0b, 0xaa, 0xa6,
	0x20, 0xa7, 0x52, 0x48, 0x80, 0x8b, 0x39, 0xb7, 0x38, 0x1d, 0xaa, 0x00, 0xc4, 0x34, 0xb2, 0xe7,
	0x62, 0x77, 0x2f, 0x4a, 0x4d, 0x2d, 0x49, 0x2d, 0x12, 0x32, 0xe1, 0xe2, 0x08, 0x4e, 0xac, 0x04,
	0xab, 0x16, 0x12, 0xd6, 0x83, 0xd8, 0x87, 0x6c, 0xbe, 0x94, 0x20, 0xaa, 0x60, 0x41, 0x4e, 0xa5,
	0x12, 0x83, 0x93, 0x1e, 0x97, 0x5c, 0x66, 0xbe, 0x5e, 0x5a, 0x66, 0x49, 0x61, 0x69, 0x66, 0x72,
	0xb6, 0x5e, 0x51, 0x41, 0xb2, 0x5e, 0x6a, 0x45, 0x62, 0x6e, 0x41, 0x4e, 0x6a, 0x31, 0x44, 0xb9,
	0x13, 0xc4, 0x01, 0x01, 0x20, 0x97, 0x07, 0x30, 0x26, 0xb1, 0x81, 0xbd, 0x60, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xfa, 0x8d, 0x63, 0x1b, 0xd1, 0x00, 0x00, 0x00,
}
